name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3  # Faz o checkout do código

      - name: Build da imagem Docker
        env:
          NVP_API_KEY: ${{ secrets.NVP_API_KEY }}
        run: docker build -t delivery-system .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout código
        uses: actions/checkout@v3  # Faz o checkout do código

      - name: Configurar Python e dependências
        run: |
          python3 -m venv venv  # Certifique-se de usar 'python3'
          source venv/bin/activate
          pip install --upgrade pip  # Atualize o pip para evitar problemas
          pip install -r requirements.txt
          pip install pytest  # Garantir instalação do pytest
          export PYTHONPATH=$PYTHONPATH:$(pwd)

      - name: Rodar testes unitários
        env:
          USUARIO: ${{ secrets.USUARIO }}
          SENHA: ${{ secrets.SENHA }}
        run: |
          source venv/bin/activate
          python3 -m pytest tests/
