name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3  # Faz o checkout do código

      - name: Build da imagem Docker
        env:
          NVP_API_KEY: ${{ secrets.NVP_API_KEY }}
        run: docker build -t delivery-system .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout código
        uses: actions/checkout@v3  # Faz o checkout do código

      - name: Instalar dependências
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Rodar testes unitários
        run: |
          source venv/bin/activate
          pytest tests/
