name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Build da imagem Docker
        run: docker build -t delivery-system .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instala dependências
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Rodar testes unitários
        run: |
          source venv/bin/activate
          pytest tests/
